# Generated by Django 2.2.1 on 2020-12-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('in_charge', models.CharField(max_length=50)),
                ('in_charge_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestock_type', models.CharField(max_length=50)),
                ('breed_category', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50)),
                ('available_stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Livestock',
                'verbose_name_plural': 'Livestocks',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField(auto_now=True)),
                ('client', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Saless',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('maturity', models.IntegerField()),
                ('maturity_period', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Farm')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Sales')),
            ],
            options={
                'verbose_name': 'SalesDetails',
                'verbose_name_plural': 'SalesDetailss',
            },
        ),
        migrations.CreateModel(
            name='FarmStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Farm')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
            ],
            options={
                'verbose_name': 'FarmStock',
                'verbose_name_plural': 'FarmStocks',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('maturity', models.IntegerField()),
                ('maturity_period', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Farm')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
            },
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Farm')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
            ],
            options={
                'verbose_name': 'Deaths',
                'verbose_name_plural': 'Deathss',
            },
        ),
        migrations.CreateModel(
            name='Births',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Farm')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuniculture_app.Livestock')),
            ],
            options={
                'verbose_name': 'Births',
                'verbose_name_plural': 'Birthss',
            },
        ),
    ]
