# Generated by Django 2.2.1 on 2021-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuniculture_app', '0002_auto_20210101_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='breed_category',
            field=models.CharField(choices=[('Breeder', 'Breeder'), ('Beef', 'Beef')], max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='maturity_period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week')], max_length=15),
        ),
    ]
