# Generated by Django 2.2.1 on 2021-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuniculture_app', '0003_auto_20210104_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='deaths',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
