# Generated by Django 2.2.1 on 2021-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuniculture_app', '0004_deaths_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deaths',
            name='cause',
            field=models.TextField(default='Fever'),
            preserve_default=False,
        ),
    ]
