# Generated by Django 2.2.1 on 2021-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuniculture_app', '0005_deaths_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
