# Generated by Django 2.2.1 on 2021-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuniculture_app', '0006_auto_20210108_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetails',
            old_name='quantity',
            new_name='female',
        ),
        migrations.AddField(
            model_name='livestock',
            name='stock_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='male',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
